### PR TITLE
utils: fix ESM import

### PR DESCRIPTION
**Pull request by ocavue**
Fixes an incorrect import for ESM.

### CODE REVIEW

**Comment by paulmillr** [comment]
the question is: why have all tests been passing?

**Comment by ocavue** [comment]
I should able to answer this question but I'm now in the bed so I will check it out tomorrow.

**Comment by paulmillr** [comment]
0.5.1 is out

**Comment by ocavue** [comment]
> why have all tests been passing



When importing a relative ESM file, ESM always requires the file extension. For example, Node.js in CommonJS module accepts both `require('./bar.js')` and `require('./bar')`, but Node.js in ESM only accepts `import './bar.js'`.

The test (`test/index.js`) is a CommonJS file, so it won't fail when the file extension (`.js`) is missing.

---

To prevent this issue, the simplest solution would be changing the `moduleResolution` from `bundler` to `Node16` in `tsconfig.esm.json`, and add `src/package.json` with the content as `{"type": "module"}`.

When using `"moduleResolution": "Node16"`, `tsc` would output CommonJS or ESM code based on the `type` field in the nearest `package.josn`. If the `type` is `"module"`, then `tsc` would generate ESM code and also check the file extension, described above.

**Comment by ocavue** [comment]
Update: I've submitted a PR to set `modeResolution` to `Node16`. 

https://github.com/paulmillr/noble-ciphers/pull/27

**Pull request closed without merging**
